CREATE POLICY "Members can view expenses" ON expenses FOR SELECT USING (EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = expenses.group_id AND gm.user_id = auth.uid()));
CREATE POLICY "Members can insert expenses" ON expenses FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = expenses.group_id AND gm.user_id = auth.uid() AND (gm.role = 'admin' OR gm.role = 'member')));
CREATE POLICY "Members can update expenses" ON expenses FOR UPDATE USING (EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = expenses.group_id AND gm.user_id = auth.uid() AND (gm.role = 'admin' OR gm.role = 'member')));
CREATE POLICY "Members can view payers" ON expense_payers FOR SELECT USING (EXISTS (SELECT 1 FROM expenses e JOIN group_members gm ON gm.group_id = e.group_id WHERE e.id = expense_payers.expense_id AND gm.user_id = auth.uid()));
CREATE POLICY "Members can insert payers" ON expense_payers FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM expenses e JOIN group_members gm ON gm.group_id = e.group_id WHERE e.id = expense_payers.expense_id AND gm.user_id = auth.uid() AND (gm.role = 'admin' OR gm.role = 'member')));
CREATE POLICY "Members can view splits" ON expense_splits FOR SELECT USING (EXISTS (SELECT 1 FROM expenses e JOIN group_members gm ON gm.group_id = e.group_id WHERE e.id = expense_splits.expense_id AND gm.user_id = auth.uid()));
CREATE POLICY "Members can insert splits" ON expense_splits FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM expenses e JOIN group_members gm ON gm.group_id = e.group_id WHERE e.id = expense_splits.expense_id AND gm.user_id = auth.uid() AND (gm.role = 'admin' OR gm.role = 'member')));
CREATE POLICY "Members can view settlements" ON settlements FOR SELECT USING (EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = settlements.group_id AND gm.user_id = auth.uid()));
CREATE POLICY "Members can create settlements" ON settlements FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = settlements.group_id AND gm.user_id = auth.uid() AND (gm.role = 'admin' OR gm.role = 'member')));
