import 'package:expense_tracker/features/expenses/data/models/expense_model.dart';
import 'package:expense_tracker/hive_registrar.g.dart';
import 'package:hive_ce/hive.dart';

/// Registers every Hive type adapter, exactly once.
abstract final class HiveAdapters {
  /// Idempotent: safe to call more than once.
  static void registerAll() {
    // The adapter list lives in hive_registrar.g.dart, generated by
    // hive_ce_generator from the @HiveType annotations. Deferring to it means
    // the list cannot drift out of sync with the models -- the hand-maintained
    // list this replaced had silently lost SettlementModelAdapter.
    //
    // The generated extension calls registerAdapter unconditionally, and Hive
    // throws when a typeId is registered twice. Probe a single adapter to keep
    // this call idempotent. Hive's own state is the right guard: adapters are
    // never unregistered, so this stays correct even across a Hive.close().
    if (Hive.isAdapterRegistered(ExpenseModelAdapter().typeId)) return;
    Hive.registerAdapters();
  }
}
