// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:expense_tracker/features/accounts/data/models/asset_account_model.dart';
import 'package:expense_tracker/features/budgets/data/models/budget_model.dart';
import 'package:expense_tracker/features/categories/data/models/category_model.dart';
import 'package:expense_tracker/features/categories/data/models/user_history_rule_model.dart';
import 'package:expense_tracker/features/expenses/data/models/expense_model.dart';
import 'package:expense_tracker/features/goals/data/models/goal_contribution_model.dart';
import 'package:expense_tracker/features/goals/data/models/goal_model.dart';
import 'package:expense_tracker/features/income/data/models/income_model.dart';
import 'package:expense_tracker/features/recurring_transactions/data/models/recurring_rule_audit_log_model.dart';
import 'package:expense_tracker/features/recurring_transactions/data/models/recurring_rule_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AssetAccountModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(GoalContributionModelAdapter());
    registerAdapter(GoalModelAdapter());
    registerAdapter(IncomeModelAdapter());
    registerAdapter(RecurringRuleAuditLogModelAdapter());
    registerAdapter(RecurringRuleModelAdapter());
    registerAdapter(UserHistoryRuleModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AssetAccountModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(GoalContributionModelAdapter());
    registerAdapter(GoalModelAdapter());
    registerAdapter(IncomeModelAdapter());
    registerAdapter(RecurringRuleAuditLogModelAdapter());
    registerAdapter(RecurringRuleModelAdapter());
    registerAdapter(UserHistoryRuleModelAdapter());
  }
}
